name = "hftq"
main = "functions/api/hftq.js"  # 确保这里是你的代码路径
compatibility_date = "2025-09-10"
preview_urls = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[secrets_store_secrets]]
binding = "HFTQURL"
store_id = "bec4e50b78f449b49e5b89b37a572d9f"
secret_name = "HFTQURL"

[[d1_databases]]
binding = "datagather"
database_name = "datagather"
database_id = "53fcc09b-cd79-40c1-8efe-5777a65dc412"