name = "hftq"
main = "functions/api/hftq.js"  # 确保这里是你的代码路径
compatibility_date = "2025-09-10"
preview_urls = true

[vars]
HFTQ_API_HOST = ""
HFTQ_API_KEY = ""

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true