name = "hftq"
main = "functions/api/hftq.js"  # 确保这里是你的代码路径
compatibility_date = "2025-09-10"
preview_urls = true

[vars]
# 你的环境变量，在这里定义，但值在 Cloudflare 或 GitHub Secrets 里设置
HFTQ_API_HOST = "https://n744u3jykn.re.qweatherapi.com"
HFTQ_API_KEY = "28bcc385aa4d4f1ab90b2d3963039d37"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true