name: 和风天气Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 wrangler CLI（因为 wrangler-action 不能直接写 secrets）
      - name: Install Wrangler
        run: npm install -g wrangler

      # 写入 Cloudflare Worker Secrets
      - name: Set Worker Secrets
        run: |
          wrangler secret put HFTQ_API_HOST --yes <<< "${{ secrets.HFTQ_API_HOST }}"
          wrangler secret put HFTQ_API_KEY --yes <<< "${{ secrets.HFTQ_API_KEY }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      # 部署 Worker
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
